### ISSUE TITLE
Multiple links to Badge Guide 404

### ISSUE THREAD

**Issue by samuelgrant** [the-ditanian-fleet/waitlist#129]
The URL for the Badge Guide has changed from `/guide/badges` to `/badges`, visiting the old URL will result in the user being shown a 404 page.

The following pages have outdated links:
- [x] First Fleet Guide
- [x] Upgrade guide (under heading "Elite")

There are two options to fix this. Either we update the URLs in the aforementioned guides to the new URL, or we update the router and navbar files so that they go back to using `/guides/badges`. This would probably be my preferred as it means our URL structure for guides is consistent. 

Let me know what option you want and I'll open a PR.

**Comment by TDF-Austar** [comment]
If you want to go ahead with option two this would be perfect! <3

**Comment by samuelgrant** [comment]
Resolved by Alex.
