### ISSUE TITLE
Inactive L badge

### ISSUE THREAD

**Issue by Lyari-Elatha** [the-ditanian-fleet/waitlist#135]
- [ ] Add it as a tag that HQ-FC can give 
- [ ] Make it show on x up
- [ ] Add it to badges guide
- [ ] Unfuck acl so they aren't all linked or whatever
- [ ] Make it so that INACTIVE cannot be invited by trainee fc (might as well do the same with nestors without L badge at the same time)
- [ ] probably something else i'm missing rn

**Comment by samuelgrant** [comment]
I've started on the Database restructure.

**Comment by samuelgrant** [comment]
This issue is mostly resolved. Working on a quality check, and then I will open a PR.
